param_grid:
  ml_model__n_estimators:
    - 150
  ml_model__max_depth:
    - 8
  under__sampling_strategy:
    - auto
    - 0.5

# Load yaml file configuration
# import yaml
# with open('rf_config.yaml', 'r') as file:
#     rf_config = yaml.safe_load(file)
